version: '3.9'

services:
  backend:
    container_name: compose-back-container
    build:
      context: ./back
      dockerfile: Dockerfile
    image: compose-backend-image
    networks:
      - backend
    ports:
      - 3001:3001
    env_file:
      - ./back/.env
    depends_on:
      - postgres
    restart: "unless-stopped"

  frontend:
    container_name: compose-front-container
    build:
      context: ./front
      dockerfile: Dockerfile
    networks:
      - frontend
    image: compose-frontend-image
    ports:
      - 3000:3000
    restart: "unless-stopped"

  postgres:
    container_name: postgres
    image: postgres
    networks:
      - backend
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    env_file:
      - ./back/.env
    ports:
      - '5432:5432'
    restart: "unless-stopped"

networks:
  frontend:
  backend:

volumes:
  postgres_data:
